### PR TITLE
[F] Adds componentDidReceiveProps (cdrp)

### PR DESCRIPTION
**Pull request by aestrro**
Adds the ability to provide componentDidReceiveProps snippets

### CODE REVIEW

**Comment by rockchalkwushock** [comment]
@aestrro 

I believe you will want `componentWillReceiveProps(nextProps)` instead:

https://facebook.github.io/react/docs/react-component.html#componentwillreceiveprops

**Comment by aestrro** [comment]
Um, yeah, that'll work too...

**Comment by aestrro** [comment]
So embarrassing! Hope this helps.

**Comment by EQuimper** [comment]
Thank you @aestrro and @rockchalkwushock  :)

**Pull request merged**
